### PR TITLE
add a new macro parameter ho, in order to reuse existing ho.

### LINKED ISSUE #23: Enable warm start
Just making a note of this for now but I would like to return to it in the future. Being able to restart a hyperopt job is pretty useful and I think the package would benefit from such a feature. 

Perhaps we could achieve this by passing the `Hyperoptimizer ` to `@hyperopt` initiation and it could infer where to resume the search?

### PR DESCRIPTION
**Pull request by norci**
so we can save ho progress periodically. or resume ho.

fixes #23

### CODE REVIEW

**Comment by baggepinnen** [comment]
Cool thanks for taking a stab at this! 
It does not appear like the new functionality is tested? There should ideally be a tests for each unique sampler as they all behave slightly differently, and some test that the number of iterations is correctly updated etc.

**Comment by norci** [comment]
I have added some test cases.
I also refactored the code, removed a few duplicate code. I'm not good at meta programming. wish these changes won't break anything.

**Comment by baggepinnen** [comment]
Cool! Are you happy with the PR and it's ready to be merged?

**Comment by norci** [comment]
Yes. I have used it for a whole day. seems OK.
Please merge it.
Thanks.

**Comment by baggepinnen** [comment]
Awesome, thanks!
A new version will be released in an hour or so :)

**Comment by baggepinnen** [comment]
It seems this might actually have broken the parallel `@phyperopt`. I noticed that you removed the `workaround_function` that was previously used to get `@phyperopt` working, can you remember the reasoning for this?

The tests had by mistake not tested parallel execution since `nworkers()` returns 1 if no additional processes have been started`

**Comment by norci** [comment]
> It seems this might actually have broken the parallel `@phyperopt` #48 . I noticed that you removed the `workaround_function` that was previously used to get `@phyperopt` working, can you remember the reasoning for this?

I'm sorry for that.
The only reason is remove redundant code. Unfortunately this mistake was not covered by the test cases :(

I just know Pkg test has a parameter "--coverage" last week.
This is very helpful.
Is there a way to generate a test coverage report locally?

**Comment by baggepinnen** [comment]
No worries, the tests certainly appeared to cover also the parallel case. The problem is solved by now. If you want to produce coverage files locally, I believe you can have coverage results printed to file with the second option below
```
 --code-coverage={none|user|all}, --code-coverage
                           Count executions of source lines (omitting setting is equivalent to "user")
 --code-coverage=tracefile.info
                           Append coverage information to the LCOV tracefile (filename supports format tokens).
```
There are also some tools for this available at https://github.com/JuliaCI/Coverage.jl

**Pull request merged**
